class AgentConstant:
    API_VERSION = '2.10.2'
    API_URL = 'https://www.szamlazz.hu/szamla/'
    CHARSET = 'UTF-8'
    COOKIE_FILENAME = 'cookie/cookie.txt'
    CERTIFICATION_FILENAME = 'cacert.pem'
    CERTIFICATION_PATH = 'cert/'
    PDF_FILE_SAVE_PATH = '.'
    XML_FILE_SAVE_PATH = '.'
    ATTACHMENTS_SAVE_PATH = './attachments'
