class SzamlaAgentException(Exception):
    """Custom exception"""
    pass

    REQUEST_TYPE_NOT_EXISTS = 'A kérés típusa nem létezik'
    SYSTEM_DOWN = 'Az oldal jelenleg karbantartás alatt áll. Kérjük, látogass vissza pár perc múlva.'
    RESPONSE_TYPE_NOT_EXISTS = 'A válasz típusa nem létezik'
    CALL_TYPE_NOT_EXISTS = 'Nem létező hívás típus'
    XML_SCHEMA_TYPE_NOT_EXISTS = 'Az XML séma típusa nem létezik'
    XML_KEY_NOT_EXISTS = 'XML kulcs nem létezik'
    XML_NOT_VALID = 'Az összeállított XML nem érvényes'
    XML_DATA_NOT_AVAILABLE = 'Hiba történt az XML adatok összeállításánál: nincs adat.'
    XML_DATA_BUILD_FAILED = 'Az XML adatok összeállítása sikertelen'
    FIELDS_CHECK_ERROR = 'Hiba a mezők ellenőrzése közben'
    CONNECTION_METHOD_CANNOT_BE_DETERMINED = 'A kapcsolódási mód típusa nem meghatározható'
    DATE_FORMAT_NOT_EXISTS = 'Nincs ilyen dátum formátum'
    NO_AGENT_INSTANCE_WITH_USERNAME = 'Nincs ilyen felhasználónévvel Számla Agent példányosítva!'
    NO_AGENT_INSTANCE_WITH_APIKEY = 'Nincs ilyen kulccsal Számla Agent példányosítva!'
    NO_SZLAHU_KEY_IN_HEADER = 'Érvénytelen válasz!'
    DOCUMENT_DATA_IS_MISSING = 'A bizonylat PDF adatai hiányoznak!'
    PDF_FILE_SAVE_SUCCESS = 'PDF fájl mentése sikeres'
    PDF_FILE_SAVE_FAILED = 'PDF fájl mentése sikertelen'
    AGENT_RESPONSE_NO_CONTENT = 'A Számla Agent válaszában nincs tartalom!'
    AGENT_RESPONSE_NO_HEADER = 'A Számla Agent válasza nem tartalmaz fejlécet!'
    AGENT_RESPONSE_IS_EMPTY = 'A Számla Agent válasza nem lehet üres!'
    AGENT_ERROR = 'Agent hiba'
    FILE_CREATION_FAILED = 'A fájl létrehozása sikertelen.'
    ATTACHMENT_NOT_EXISTS = 'A csatolandó fájl nem létezik'
    SENDING_ATTACHMENT_NOT_ALLOWED = 'Számlamelléklet csatolása csak CURL kérés esetén támogatott!'
    INVOICE_NOTIFICATION_SEND_FAILED = 'Számlaértesítő kézbesítése sikertelen'
    INVALID_JSON = 'Érvénytelen JSON'
